#org.gradle.console=plain
org.gradle.java.home=/lib/jvm/java-25-openjdk

# Gradle 9 recommendation
# https://docs.gradle.org/current/userguide/configuration_cache_enabling.html#config_cache:usage:enable
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.configuration-cache.max-problems=1
